### ISSUE TITLE
undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by maxadamo** [albatrossflavour/puppet_os_patching#202]
## Affected Puppet, Ruby, OS, and module versions/distributions

- Puppet: N/A
- Ruby: N/A
- Distribution: N/A
- Module version: 0.15

## How to reproduce (e.g Puppet code you use)

this is happening when the key `ensure` in the JSON catalog does not exist. 
My guess is that when the `package` resource is used without `ensure`, the default key "present", is not being added to the catalog. For instance: `package { 'my-package': }` will not create a proper entry in the catalog

## What are you seeing

on some servers I am seeing this error: 

```
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from -e:1:in `select'
-e:1:in `block in <main>': undefined method `match' for nil:NilClass (NoMethodError)
```

## What behavior did you expect instead

Please check the PR https://github.com/albatrossflavour/puppet_os_patching/pull/203 for a possible solution. 
We need to ensure that the key exists before attempting to match the digits.

**Comment by maxadamo** [comment]
My guess is probably correct. 
In the following line you see a piece of code that is causing me the issue that I was describing: 
https://github.com/maxadamo/galera_proxysql/blob/master/manifests/galera/install.pp#L28

**Comment by albatrossflavour** [comment]
Fixed as part of #203

**Comment by maxadamo** [comment]
@albatrossflavour it seems that version 0.16 does not include this change

**Comment by FrankVanDamme** [comment]
This piece of code doesn't seem to be in 0.19 and adding it manually does not fix the error for me (message remains the same). Puppet 7.23, puppetserver 7.9.5.

**Comment by albatrossflavour** [comment]
Hmmm, odd.  Can you share any steps to reproduce it?

**Comment by FrankVanDamme** [comment]
I figured it out. I have packages with no parameters whatso-ever so also inserting a check "and r['parameters']" fixes it (for me).
